In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
column_names = ["Inode (file unique ID)",
"KB Allocated",
"File Size",
"Creation Time in days from today",
"Change Time in days from today",
"Modification time in days from today",
"Acces time in days from today",
"GID numeric ID for the group owner of the file",
"UID numeric ID for the owner of the file"]
GPFS = pd.read_csv("/mnt/research/CMSE495-SS24-ICER/file_system_usage/gpfs-stats/inode-size-age-jan-23",header=None, names = column_names, sep=" ",nrows=1e7)
GPFS

,Inode (file unique ID),KB Allocated,File Size,Creation Time in days from today,Change Time in days from today,Modification time in days from today,Acces time in days from today,GID numeric ID for the group owner of the file,UID numeric ID for the owner of the file
0,100663296,0,8,1447,1447,3131,1447,2035,762231
1,100663297,0,188,1447,1447,1937,1447,2010,614955
2,100663301,0,567,1447,1447,3142,1447,2035,762231
3,100663304,0,87,1447,1447,3142,1447,2035,762231
4,100663306,0,1689,1447,1447,1937,1447,2010,614955
...,...,...,...,...,...,...,...,...,...
9999995,124522107,64,5739,15,15,146,2,2005,6052828
9999996,124522107,64,5739,15,15,146,2,2005,6052828
9999997,124522108,0,1051,15,15,161,15,2005,6052828
9999998,124522108,0,1051,15,15,161,15,2005,6052828
9999999,124522109,64,3864,15,15,111,15,2005,6052828

# Users With Many Files

In [15]:
# Count the number of files for each user  ****************
file_count_per_user = GPFS.groupby("UID numeric ID for the owner of the file").size()

# Display the result
file_countperUID= file_count_per_user[file_count_per_user>1000]
file_countperUID

UID numeric ID for the owner of the file
0               1039
500120        655392
614955        677944
638741        835389
697349        305850
753559        383946
758827        264003
762231        856363
785573        776204
799192         21128
831677        366721
834474         50287
839641        922130
841154        526494
862983        303210
875212         84531
876249        315345
881083        915468
1028735        21466
1040196       503224
1040612       182603
6052828       352409
1000000088    195906
1000000092    481751
dtype: int64

In [24]:
# identify users with many files
def UsersWithManyFiles(data, file_limit):
    '''
    Function to identify users with many files using a file limit 
    as a number integer of the limit of number of files per user.

    args:
        data - dataset containing columns related to user
        file_limit - integer resembling the file limit per user
    
    returns: 
        a dataframe of users that are have a greater number of total files than the 
        file limit.

    '''

    # Group by the user ID and count the number of files for each user
    file_count_per_user = data.groupby("UID numeric ID for the owner of the file").size()
    
    # Filter users who have more files than the file_limit
    users_with_many_files = file_count_per_user[file_count_per_user > file_limit]
    
    # Convert the filtered Series object to a DataFrame
    users_with_many_files_df = users_with_many_files.reset_index()
    
    users_with_many_files_df.columns = ['UID numeric ID for the owner of the file', 'Number of files']
    
    
    # Sort by 'Number of files' in descending order
    users_with_many_files_df.sort_values('Number of files', ascending=False, inplace=True)
    
    return users_with_many_files_df

# test, setting file limit= 10,000
UsersWithManyFiles(GPFS,10000)

    UID numeric ID for the owner of the file  Number of files
11                                    839641           922130
16                                    881083           915468
6                                     762231           856363
2                                     638741           835389
7                                     785573           776204
1                                     614955           677944
0                                     500120           655392
12                                    841154           526494
18                                   1040196           503224
22                                1000000092           481751
4                                     753559           383946
9                                     831677           366721
20                                   6052828           352409
15                                    876249           315345
3                                     697349           305850
13                                    862983           303210
5                                     758827           264003
21                                1000000088           195906
19                                   1040612           182603
14                                    875212            84531
10                                    834474            50287
17                                   1028735            21466
8                                     799192            21128